version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - database
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=Europe/Moscow

  server:
    build: ./server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/shareit
      - TZ=Europe/Moscow

  database:
    image: postgres:14.5-alpine
    container_name: database
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
