CREATE TABLE IF NOT EXISTS users (
     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     user_name VARCHAR(255) NOT NULL,
     user_email VARCHAR(512) NOT NULL,
     CONSTRAINT pk_user PRIMARY KEY (user_id),
     CONSTRAINT UQ_USER_EMAIL UNIQUE (user_email)
);

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    item_name varchar(1000),
    item_description VARCHAR(1000),
    item_available boolean,
    CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(user_id), UNIQUE(user_id) );

-- DELETE FROM users;
-- DELETE FROM items;
-- drop table items;